function Hd = lp_iir(Fs,Fpass,Fstop,Apass,Astop)
%LP_IIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 18-Jan-2014 01:35:02

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
% Fs = 48000;  % Sampling Frequency
% 
% Fpass = 200;         % Passband Frequency
% Fstop = 800;         % Stopband Frequency
% Apass = 1;           % Passband Ripple (dB)
% Astop = 60;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
