function Hd = butterwoth_LP_design(Fpass,Fstop,Apass,Astop,Fs)
%BUTTERWOTH_LP_DESIGN Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 28-Jan-2015 18:39:20

% Fpass = 2;   % Passband Frequency
% Fstop = 5;   % Stopband Frequency
% Apass = 1;   % Passband Ripple (dB)
% Astop = 60;  % Stopband Attenuation (dB)
% Fs    = 50;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'butter', ...
    'MatchExactly', 'stopband', ...
    'SystemObject', true);



