function Hd = highpass_iir(Fs,Fstop,Fpass,Astop,Apass)
%HIGHPASS_IIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 18-Jan-2014 18:49:33

% Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
% Fs = 48000;  % Sampling Frequency
% 
% Fstop = 10;          % Stopband Frequency
% Fpass = 150;         % Passband Frequency
% Astop = 60;          % Stopband Attenuation (dB)
% Apass = 1;           % Passband Ripple (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
