function Hd = notch_generator(Fs,Fpass1,Fstop1,Fstop2,Fpass2,Apass1,Astop,Apass2)
%NOTCH_GENERATOR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 18-Jan-2014 01:26:28

% Butterworth Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
% Fs = 48000;  % Sampling Frequency

% Fpass1 = 7200;        % First Passband Frequency
% Fstop1 = 9600;        % First Stopband Frequency
% Fstop2 = 12000;       % Second Stopband Frequency
% Fpass2 = 14400;       % Second Passband Frequency
% Apass1 = 0.5;         % First Passband Ripple (dB)
% Astop  = 60;          % Stopband Attenuation (dB)
% Apass2 = 1;           % Second Passband Ripple (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
