function Hd = Fir_windows_generator(order,Fc_normalized)
%FIR_WINDOWS_GENERATOR Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
%
% Generated on: 05-Sep-2014 06:07:18
%

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are normalized to 1.

% N    = 240;      % Order
% Fc   = 0.008;    % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(order+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(order, Fc_normalized, 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
