function Hd = Iir_butterwoth_generator(Fpass_norm,Fstop_norm,pass_db,stop_db)
%IIR_BUTTERWOTH_GENERATOR Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
%
% Generated on: 06-Sep-2014 00:54:54
%

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are normalized to 1.

match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass_norm, Fstop_norm, pass_db, stop_db);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
